version: "3.3"

services:
  db:
    image: postgres:latest
    container_name: postgres-polestar-service
    hostname: postgres-polestar-service
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
    environment:
      POSTGRES_DB: "test_polestar_db"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "P@ssw0rd"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    command: [ "postgres", "-c", "log_statement=all", "-c", "fsync=off", "-c", "synchronous_commit=off", "-c", "full_page_writes=off" ]
    ports:
      - "5432:5432"
    networks:
      - default

  service:
    container_name: polestar
    hostname: polestar
    image: polestar
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: "test"

    volumes:
      - "/tmp:/tmp"

    ports:
      - "8000:8000"

    depends_on:
      - db
    
    environment:
      - DATABASE_NAME=test_polestar_db
      - DATABASE_USER=test
      - DATABASE_PASSWORD=P@ssw0rd
      - DATABASE_HOST=postgres-polestar-service
      - DATABASE_PORT=5432

    
    networks:
      - default



volumes:
  citests:

networks:
  default:
